name: crayola
description: A plugin for customising desktop app window properties.
version: 0.0.1
homepage: https://github.com/arnemolland/crayola

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      macos:
        pluginClass: CrayolaPlugin
