name: crayola
description: A plugin for customizing Flutter desktop app window properties. Currently macOS only.
version: 2.0.0
homepage: https://github.com/arnemolland/crayola

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      macos:
        pluginClass: CrayolaPlugin
