name: crayola
description: A plugin for customizing Flutter desktop app window properties. Currently macOS only.
version: 2.2.0
homepage: https://github.com/arnemolland/crayola

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=2.8.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.1
  markdown: ^7.0.1
  yaml: ^3.1.1
  args: ^2.4.0
  collection: ^1.17.1
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      macos:
        pluginClass: CrayolaPlugin
