name: crayola
description: A plugin for customising Flutter desktop app window properties. Currently macOS only.
version: 1.0.0+1
homepage: https://github.com/arnemolland/crayola

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      macos:
        pluginClass: CrayolaPlugin
