on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*"

jobs:
  dryrun:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          channel: master
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - uses: rlespinasse/github-slug-action@v4.4.1

      - name: Set release version
        run: echo RELEASE_VERSION=$(echo ${{ env.GITHUB_REF_SLUG }}|cut -c2-) >> $GITHUB_ENV

      - name: Verify changelog exists
        run: dart tool/validate.dart -t ${{ env.RELEASE_VERSION }}

  publish:
    needs: dryrun
    # Docs found at https://dart.dev/tools/pub/automated-publishing
    uses: dart-lang/setup-dart/.github/workflows/publish.yml@v1
